import csv
import math
import pandas as pd

import config as cfg
from data_manager import fetch_klines
from indicators import add_indicators
from strategy import long_signal, short_signal, exit_signal

def execution_price(price, side, is_entry, slippage):
    # Conservative slippage model:
    # Long entry / Short exit => pay slightly more
    # Short entry / Long exit => receive slightly less
    if (side == "LONG" and is_entry) or (side == "SHORT" and not is_entry):
        return price * (1 + slippage)
    return price * (1 - slippage)

def commission(notional):
    return notional * cfg.FEE_RATE

def run_backtest(df):
    equity = cfg.INITIAL_CAPITAL
    position = None
    entry_price = None
    entry_time = None
    entry_notional = None
    entry_fee = 0.0

    trades = []
    equity_curve = []

    # Signals are calculated on CLOSED candle i.
    # Execution occurs at the NEXT candle OPEN.
    pending_entry = None
    pending_exit = False

    for i in range(len(df)):
        row = df.iloc[i]

        # Execute orders generated by previous closed candle at current open.
        if pending_exit and position is not None:
            exit_side = position
            px = execution_price(float(row["open"]), exit_side, False, cfg.SLIPPAGE_RATE)

            if position == "LONG":
                pnl_gross = (px - entry_price) * (entry_notional / entry_price)
            else:
                pnl_gross = (entry_price - px) * (entry_notional / entry_price)

            exit_fee = commission(abs(px * (entry_notional / entry_price)))
            pnl_net = pnl_gross - entry_fee - exit_fee
            equity += pnl_gross - exit_fee

            trades.append({
                "entry_time": entry_time,
                "exit_time": row["open_time"],
                "side": position,
                "entry_price": entry_price,
                "exit_price": px,
                "gross_pnl": pnl_gross,
                "fees": entry_fee + exit_fee,
                "net_pnl": pnl_net,
                "return_pct_on_equity": pnl_net / max(equity - pnl_gross + exit_fee, 1e-12),
                "reason": "EMA100_CLOSE",
            })

            position = None
            entry_price = entry_time = entry_notional = None
            entry_fee = 0.0
            pending_exit = False

        if pending_entry is not None and position is None:
            side = pending_entry
            px = execution_price(float(row["open"]), side, True, cfg.SLIPPAGE_RATE)

            entry_notional = equity * cfg.POSITION_SIZE_PCT * cfg.LEVERAGE
            entry_fee = commission(entry_notional)
            equity -= entry_fee

            position = side
            entry_price = px
            entry_time = row["open_time"]
            pending_entry = None

        # Record mark-to-market equity at current close.
        marked_equity = equity
        if position is not None:
            qty = entry_notional / entry_price
            if position == "LONG":
                unrealized = (float(row["close"]) - entry_price) * qty
            else:
                unrealized = (entry_price - float(row["close"])) * qty
            marked_equity += unrealized

        equity_curve.append({
            "time": row["close_time"],
            "equity": marked_equity,
            "position": position or "FLAT",
        })

        # Generate signals only after the candle is fully closed.
        if i < len(df) - 1:
            if position is not None:
                if exit_signal(position, row):
                    pending_exit = True
            else:
                if long_signal(df, i, cfg):
                    pending_entry = "LONG"
                elif short_signal(df, i, cfg):
                    pending_entry = "SHORT"

    # Close any remaining position at final close for complete accounting.
    if position is not None:
        row = df.iloc[-1]
        px = execution_price(float(row["close"]), position, False, cfg.SLIPPAGE_RATE)
        qty = entry_notional / entry_price
        if position == "LONG":
            pnl_gross = (px - entry_price) * qty
        else:
            pnl_gross = (entry_price - px) * qty

        exit_fee = commission(abs(px * qty))
        pnl_net = pnl_gross - entry_fee - exit_fee
        equity += pnl_gross - exit_fee

        trades.append({
            "entry_time": entry_time,
            "exit_time": row["close_time"],
            "side": position,
            "entry_price": entry_price,
            "exit_price": px,
            "gross_pnl": pnl_gross,
            "fees": entry_fee + exit_fee,
            "net_pnl": pnl_net,
            "return_pct_on_equity": pnl_net / max(equity - pnl_gross + exit_fee, 1e-12),
            "reason": "END_OF_DATA",
        })

    return pd.DataFrame(trades), pd.DataFrame(equity_curve), equity

def calculate_metrics(trades, equity_curve):
    if equity_curve.empty:
        return {}

    eq = equity_curve["equity"]
    peak = eq.cummax()
    drawdown = eq / peak - 1.0
    max_dd = drawdown.min()

    net_profit = trades["net_pnl"].sum() if not trades.empty else 0.0
    wins = trades[trades["net_pnl"] > 0] if not trades.empty else pd.DataFrame()
    losses = trades[trades["net_pnl"] <= 0] if not trades.empty else pd.DataFrame()

    gross_profit = wins["net_pnl"].sum() if not wins.empty else 0.0
    gross_loss = abs(losses["net_pnl"].sum()) if not losses.empty else 0.0

    pf = gross_profit / gross_loss if gross_loss > 0 else math.inf
    win_rate = len(wins) / len(trades) if len(trades) else 0.0
    expectancy = net_profit / len(trades) if len(trades) else 0.0

    long_trades = trades[trades["side"] == "LONG"] if not trades.empty else pd.DataFrame()
    short_trades = trades[trades["side"] == "SHORT"] if not trades.empty else pd.DataFrame()

    return {
        "initial_capital": cfg.INITIAL_CAPITAL,
        "final_equity": float(eq.iloc[-1]),
        "net_profit": float(net_profit),
        "return_pct": float((eq.iloc[-1] / cfg.INITIAL_CAPITAL - 1) * 100),
        "trades": int(len(trades)),
        "wins": int(len(wins)),
        "losses": int(len(losses)),
        "win_rate_pct": float(win_rate * 100),
        "profit_factor": float(pf),
        "expectancy_per_trade": float(expectancy),
        "max_drawdown_pct": float(max_dd * 100),
        "long_trades": int(len(long_trades)),
        "short_trades": int(len(short_trades)),
        "long_win_rate_pct": float((long_trades["net_pnl"] > 0).mean() * 100) if len(long_trades) else 0.0,
        "short_win_rate_pct": float((short_trades["net_pnl"] > 0).mean() * 100) if len(short_trades) else 0.0,
    }

def main():
    print(f"Downloading {cfg.SYMBOL} {cfg.INTERVAL} data...")
    df = fetch_klines(cfg.SYMBOL, cfg.INTERVAL, cfg.DATA_START, cfg.DATA_END)

    print(f"Rows: {len(df):,}")
    print("Calculating indicators...")
    df = add_indicators(df, cfg)

    print("Running backtest...")
    trades, equity_curve, final_equity = run_backtest(df)

    metrics = calculate_metrics(trades, equity_curve)

    trades.to_csv(cfg.TRADES_CSV, index=False)
    equity_curve.to_csv(cfg.EQUITY_CSV, index=False)

    print("\n========== BACKTEST RESULT ==========")
    for k, v in metrics.items():
        if isinstance(v, float):
            print(f"{k:25s}: {v:.4f}")
        else:
            print(f"{k:25s}: {v}")
    print("=====================================\n")
    print(f"Trades saved: {cfg.TRADES_CSV}")
    print(f"Equity saved: {cfg.EQUITY_CSV}")

if __name__ == "__main__":
    main()
